#' Show Command
#'
#' Call the the various `show` commands and return results as a tibble.
#'
#' @param type The type of thing to show.
#' @param pattern Pattern to filter results. Uses `LIKE` style filtering.
#' @param n Number of rows to return. Use `-1` to show all rows.
#' @param con A connection object. Typically generated by [flaky_connect()].
#'
#' @return Tibble of results
#' @export
#'
#' @examples
#' \dontrun{
#' # Show 50 warehouses
#' flaky_show("warehouses")
#'
#' # Show all functions
#' flaky_show("functions", n = -1)
#'
#' # Show the azure regions
#' flaky_show("regions", "AZURE%")
#' }
flaky_show <- function(type, pattern, n = 50, con = getOption("flaky.con")) {

  sql_cmd <- paste0("show ", type)

  if (!missing(pattern)) {
    sql_cmd <- paste0(sql_cmd, " LIKE '", pattern, "'")
  }

  dplyr::as_tibble(DBI::dbGetQuery(con, sql_cmd, n = n))
}

#' List possible show commands
#'
#' Parses Snowflake docs for show commands and provides as a tibble.
#'
#' @param pattern Pattern to detect in name of show command. Uses [stringr::str_detect()].
#'
#' @return tibble
#' @export
#'
#' @examples
#' \dontrun{
#'  # Return all shows
#'  flaky_show_ls()
#'
#'  # Find function ones
#'  flaky_show_ls("fun")
#'
#'  # Combine with flaky_show
#'  flaky_show_ls() %>% slice(1) %>% pull(name) %>% flaky_show()
#' }
flaky_show_ls <- function(pattern) {
  base_list <-
    tibble(name =
      httr::GET("https://docs.snowflake.net/manuals/sql-reference/sql/show.html") %>%
      xml2::read_html() %>%
      rvest::html_nodes("span[class=doc]") %>%
      rvest::html_text() %>%
      stringr::str_extract("SHOW .+") %>%
      na.omit() %>%
      stringr::str_remove("SHOW ") %>%
      tolower() %>%
      unique() %>%
      sort()
    )

  if (!missing(pattern)) {
    return(
      base_list %>%
        dplyr::filter(stringr::str_detect(name, tolower(pattern)))
    )
  }

  base_list
}
