#' Remove data from Snowflake
#'
#' Remove a table from Snowflake. Ensures schema and table names are uppercase.
#'
#' @param table_schema Name of target schema.
#' @param table_name Name of target table.
#' @param ... Additional parameters to pass on to [DBI::dbRemoveTable()].
#' @param con A connection object. Typically generated by [flaky_connect()].
#'
#' @export
#'
#' @examples
#' \dontrun{
#' flaky_remove(table_schema = "rdata", table_name = "mtcars")
#' }
flaky_remove <- function(table_schema, table_name, ..., con = getOption("flaky.con")) {
  DBI::dbRemoveTable(
    con = con,
    name = DBI::Id(schema = toupper(table_schema), table = toupper(table_name)),
    ...
  )
}
